music/urls.py
from django.conf.urls import url
from . import views

app_name = 'music'

urlpatterns = [
	# /music/
	# url(r'^$', views.index, name = 'index'),
	url(r'^$', views.IndexView.as_view(), name = 'index'),
	# /music/<album_id>/
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),#previously album_id for pk
	# /music/<album_id>/favorite/
	# url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
	url(r'album/add/$', views.AlbumCreate.as_view(), name='album-add')
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
]

music/models.py
from __future__ import unicode_literals

from django.db import models
from django.urls import reverse

# Create your models here.
class Album(models.Model):
	artist = models.CharField(max_length=250)
	album_title = models.CharField(max_length=500)
	genre = models.CharField(max_length=100)
	album_logo = models.CharField(max_length=1000)

	def get_absolute_url(self):
		return reverse('music:detail', kwargs={'pk' : self.pk})

	def __str__(self):
		return self.album_title + " - " + self.artist

class Song(models.Model):
	album = models.ForeignKey(Album, on_delete=models.CASCADE)
	file_type = models.CharField(max_length=10)
	song_title = models.CharField(max_length=250)
	is_favorite = models.BooleanField(default=False)

	def __str__(self):
		return self.song_title

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Album

class IndexView(generic.ListView):
	template_name = 'music/index.html'
	context_object_name = 'all_albums'

	def get_queryset(self):
		return Album.objects.all()

class DetailView(generic.DetailView):
	model = Album
	template_name = 'music/detail.html'

class AlbumCreate(CreateView):
	model = Album
	fields = ['artist', 'album_title', 'genre', 'album_logo']

music/templates/music/base.html
<!DOCTYPE html>
<html lang='en'>

<head>
	<meta charset='UTF-8'>
	<title>{% block title %}Bat's Cave{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" type="text/css" href="{% static 'music/style.css' %}" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
	<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
	<nav class="navbar navbar-inverse">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type='button' class='navbar-toggle' data-toggle='collapse' data-target='#topNavBar'>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
					<span class='icon-bar'></span>
				</button>
				<a class="navbar-brand" href="{% url 'music:index' %}">BatCave</a>
			</div>

			<div class='collapse navbar-collapse' id='topNavBar'>

				<ul class='nav navbar-nav'>
					<li class=''>
						<a href="{% url 'music:index' %}">
							<span class='glyphicon glyphicon-cd' aria-hidden='true'></span>
							&nbsp; Albums
						</a>
					</li>

					<li class=''>
						<a href='#'>
							<span class='glyphicon glyphicon-music' aria-hidden='true'></span>
							&nbsp; Songs
						</a>
					</li>
				</ul>

				<form class='navbar-form navbar-left' role='search' method='get' action='#'>
					<div class='form-group'>
						<input type='text' class='form-control' name='q' value=''>
					</div>
					<button type='submit' class='btn btn-default'>Search</button>
				</form>

				<ul class='nav navbar-nav navbar-right'>
					<li class=''>
						<a href='#'>
							<span class='glyphicon glyphicon-plus' aria-hidden='true'></span>
							&nbsp; Add Album
						</a>
					</li>
					<li class=''>
						<a href='#'>
							<span class='glyphicon glyphicon-off' aria-hidden='true'></span>
							&nbsp; Logout
						</a>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	{% block body %}
	{% endblock %}
</body>

music/templates/music/detail.html
{% extends 'music/base.html' %}

{% block title %}
Album Details
{% endblock %}

{% block body %}
<img src="{{ album.album_logo }}" width='200' height='200'>

<h1>{{ album.album_title }}</h1>
<h2>{{ album.artist }}</h2>

{% for song in album.song_set.all %}
	{{ song.song_title }}
	{% if song.is_favorite %}
		<img src="https://cdn4.iconfinder.com/data/icons/small-n-flat/24/star-128.png" />
	{% endif %}
	<br>
{% endfor %}

{% endblock %}

music/templates/music/detailx.html
{% extends 'music/base.html' %}
{% block title %}{{ album }}{% endblock %}
{% block body %}

<div class="container-fluid songs-container">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <a href="{% url 'music:detail' album.id %}">
                        {% if album.logo %}
                            <img src="{{ album.logo }}" class="img-responsive">
                        {% else %}
                            <h3>No image to display</h3>
                        {% endif %}
                    </a>
                    <h1>{{ album.title }} <small>{{  album.genre }}</small></h1>
                    <h2>{{ album.artist }}</h2>
                </div>
            </div>
        </div>

        <!-- Right Song Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation" class="active"><a href="{% url 'music:detail' album.id %}">View All</a></li>
                <li role="presentation"><a href="#">Add New Song</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">

                    <h3>All Songs</h3>

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}

                    <table class="table">
                        <thead>
                        <tr>
                            <th>Title</th>
                            <th>Audio File</th>
                            <th>Favorite</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for song in album.song_set.all %}
                            <tr>
                                <td>{{ song.title }}</td>
                                <td>
                                    <a target="_blank" href="#">
                                        <button type="button" class="btn btn-success btn-xs">
                                            <span class="glyphicon glyphicon-play"></span>&nbsp; Play
                                        </button>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" class="btn-favorite"><span class="glyphicon glyphicon-star {% if song.is_favorite %}active{% endif %}"></span></a>
                                </td>
                                <td>
                                    <form action="#" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="song_id" value="{{ song.id }}" />
                                        <button type="submit" class="btn btn-danger btn-xs">
                                            <span class="glyphicon glyphicon-remove"></span>&nbsp; Delete
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block title %}
Bat's Cave
{% endblock %}

{% block body %}
<!-- {% if all_albums %} -->
	<h3> All the albums under hood</h3>
	<ul>
		{% for album in all_albums %}
		<!-- <li><a href="/music/{{ album.id }}/">{{ album.album_title}}</a></li> -->
		<li><a href="{% url 'music:detail' album.id %}">{{ album.album_title }}</a></li>
		{% endfor %}
	</ul>
<!-- {% else %}
	<h3>You don't have any albums</h3>
{% endif %} -->
{% endblock %}

music/templates/music/indexx.html
{% extends 'music/base.html' %}

{% block body %}

<div class="albums-container container-fluid">

    <!-- Albums -->
    <div class="row">
        <div class="col-sm-12">
            <h3>Available Albums</h3>
        </div>
            {% if all_albums %}
                {% for album in all_albums %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'music:detail' album.id %}">
                            <img src="{{ album.logo}}" class="img-responsive">
                        </a>
                        <div class="caption">
                            <h2>{{ album.album_title }}</h2>
                            <h4>{{ album.artist }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'music:detail' album.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Album -->
                            <form action="#" method="post" style="display: inline;">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}" />
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>

                            <!-- Favorite Album -->
                            <a href="#" class="btn btn-default btn-sm btn-favorite" role="button">
                                <span class="glyphicon glyphicon-star"></span>
                            </a>

                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="#">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>

{% endblock %}